### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by Enigma94** [atom/metrics#51] opened 2015-07-01 03:15 UTC
I would like reporting to google to be turned off by default. Many people have trust issues with google and are uneasy about using anything by them, and knowing Atom is built on Chrome is a bit unsettling. Until we have more information I'm going to another editor and recommend others to do the same.

**Comment by thomasjo** [comment] 2015-07-01 05:01
Duplicate of #16 and #25.

@atom/feedback Maybe it's time we reconsider having this enabled by default when not giving an explicit opt-out option on e.g. the *welcome screen*? Closing as a dupe regardless.

**Closed by thomasjo** 2015-07-01 05:01 UTC
